### ISSUE TITLE
No commands possible with rm4 pro

### ISSUE THREAD

**Issue by Wuijsman** [shaarkys/com.broadlink#2]
I recently bought a rm4 pro mini and connected it with the homey broadlink app to homey. In my Homey app I can now see the rm 4. When I open it I get two buttons. One for learning a rf command and one for the IR command. When I press the rf button the only thing that happens is that I get a message that I have to press a button on the rf set. I press a button and after a short while I get the message that it failed. The same result with the IR button. There are no leds on in the rm4 pro unit. In the rm4 I have programmed several buttons and they work well. Please can you help me with this problem.

Martin Wuijsman
wuijsman@hotmail.com

**Comment by fernanpizarro** [comment]
Hi, i recently did the same as Wuijsman and had the same result. No IR learning, with the same error problem.

Here's another question... Do you know if is there a way to connect to broadlink cloud and acces to the sub-devices defined in broadlink app?

**Comment by najlind** [comment]
Hi, same experience here with a rm4 mini I just bought.   IR learning fails.   The rm4 works fine from the IOS App.  Please advise.

Regards
Jan

**Comment by shaarkys** [comment]
Please check the latest versions and submit logs if the issues persist and re-open this issue.

> When I open it I get two buttons.
If you see two buttons, you have not added RM4 Mini but RM4 Pro ...

> rm4 pro mini
> rm4 pro
But you mentioned both... not sure.

For RM4 Pro you must not have latest firmware installed, see the forum  - https://community.homey.app/t/app-pro-broadlink-app/6389


> Hi, i recently did the same as Wuijsman and had the same result. No IR learning, with the same error problem.
> rm4 mini I just bought. IR learning fails.

Please generate log from Broadlink app... also ensure you don't have your device LOCKED in the original app.

> Do you know if is there a way to connect to broadlink cloud and acces to the sub-devices defined in broadlink app?

Unfortunately I doubt, if I'm not mistaken, none of the integration has it.

Closing this now, feel free to reopen if needed.

**Comment by najlind** [comment]
Problem for me was that device was LOCKED in the original app.   Thanks for your help!  :-)
